language: android
os: linux
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29
branches:
  only:
    - master
jobs:
  include:
    - stage: lint
      script: git update-index --chmod=+x gradlew && ./gradlew ktlintCheck